name: autocomplete_plus
description: "Effortless API-driven autocomplete for Flutter, featuring seamless infinite scrolling to handle massive datasets with ease."
version: 0.0.1
homepage: https://github.com/NamTranDinh/autocomplete_plus
documentation: https://github.com/NamTranDinh/autocomplete_plus/blob/main/README.md
repository: https://github.com/NamTranDinh/autocomplete_plus
issue_tracker: https://github.com/NamTranDinh/autocomplete_plus/issues
topics:
  - autocomplete
  - infinite-scroll
  - suggestion
keywords:
  - autocomplete
  - suggestion
  - infinite scrolling
  - search

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0